# Datenbank
spring:
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

mailgun:
  api-key: ${MAILGUN_API_KEY}
  domain: ${MAILGUN_DOMAIN:mazari-autovermietung.com}
  base-url: ${MAILGUN_BASE_URL:https://api.eu.mailgun.net}

server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${APP_SECRET}
    expiration-ms: 86400000 # 24 Stunden
  frontend:
    base-url: ${FRONTEND_BASE_URL:http://localhost:5173}

  email:
    from: "Mazari Autovermietung <no-reply@mazari-autovermietung.com>"

# Zahlung mit Stripe
stripe:
  secret-key: ${SK_TEST}
  public-key: ${PK_TEST}
  webhookSecret: ${WEBHOOK_SECRET}

# Optional: falls du später Mailgun-HTTP-API nutzt
#mailgun:
#  domain: sandboxb512a2e8274842b7b0381a94003c3302.mailgun.org
#  apiKey: key-xxxxxxxxxxxxxxxxxxx
