# Datenbank
spring:
  datasource:
    url: jdbc:h2:mem:autovermietungdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  mail:
    host: smtp.mailgun.org          # oder smtp.eu.mailgun.org (je nach Mailgun-Region)
    port: 587
    username: mazari@sandboxb512a2e8274842b7b0381a94003c3302.mailgun.org
    password: Mazari                # lokal ok, später über ENV-Var lösen
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${PORT:8080}

# Für die Anwendung (JWT & E-Mails)
app:
  jwt:
    secret: Vqa6JP4YddRBAu9zuQAlRCmiq7wx21zjOTbeqaCDSAYh7rRpocbJ5aNLyNy/kvzlcCJ9xitP2IfjpH6mpLKXLA== # 32+ Zeichen Base64
    expiration-ms: 86400000 # 24 Stunden

  email:
    from: "Autovermietung <noreply@sandboxb512a2e8274842b7b0381a94003c3302.mailgun.org>"

# Zahlung mit Stripe
stripe:
  secret-key: sk_test_51SYW7k7cWPpddEzaUiMoHrXy9Zxqx8dMtsmDmNlP8dX4q9AWfQlTcjkGys8xQazxNFMqjWLD7BpAkVtiQEBN7XFb0067TJZtfx
  public-key: pk_test_51SYW7k7cWPpddEzaLzJ7bYXOpu4f9D1734k7WYEFFbQ51VrkYALdm8sgJRnP0QgHyrXEDxy8tVRDPYMjq5a8gaOu00DpviD6vk
  webhookSecret: whsec_3XmiblPX86CUdjKQnaxjCZYxEquemgOS

# Optional: falls du später Mailgun-HTTP-API nutzt
#mailgun:
#  domain: sandboxb512a2e8274842b7b0381a94003c3302.mailgun.org
#  apiKey: key-xxxxxxxxxxxxxxxxxxx
